// Tailwind config for the design-sync build.
//
// The design agent writes NEW markup — utilities this repo never happens to use
// must still be present, or its designs render unstyled. The content globs only
// cover the repo's own files, so `.tw-safelist.html` (generated by
// gen-safelist.mjs) enumerates the rest of the vocabulary as literal candidates.
//
// This is deliberately NOT `safelist: [{pattern: /./, variants: [...]}]` — that
// is a combinatorial explosion that OOMs the build rather than finishing.
import base from "../tailwind.config"
import type { Config } from "tailwindcss"

const config: Config = {
  ...base,
  content: [
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx}",
    "./.design-sync/previews/**/*.{ts,tsx}",
    "./.design-sync/.tw-safelist.html",
  ],
}

export default config
